apiVersion: v1
kind: Namespace
metadata:
  name: fluentd-demo
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd-spring-boot-poc
  namespace: fluentd-demo
  labels:
    app: fluentd-spring-boot-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd-spring-boot-poc
  template:
    metadata:
      labels:
        app: fluentd-spring-boot-poc
    spec:
      containers:
        - name: fluentd-spring-boot-poc
          image: localhost:5000/spring-boot-fluentd:v1
          imagePullPolicy: Always